version: '3.7'

services:

  api:
    build:
      context: ./api/
      target: ${NODE_ENV}
    volumes:
    - ./api:/usr/src/app
    - /usr/src/app/node_modules
    restart: always
    env_file:
    - .env
    ports:
    - ${VITE_API_PORT}:${VITE_API_PORT}
    networks:
    - ft_transcendence_network
    container_name : api
    hostname: api
    depends_on:
    - postgreSQL
    command: npm run start:${NODE_ENV}

  front:
    build:
      context: ./front-end/
    volumes:
    - ./front-end:/usr/src/app
    - /usr/src/app/node_modules
    restart: always
    environment:
      FRONT_PORT: ${FRONT_PORT}
    ports:
    - ${FRONT_PORT}:${FRONT_PORT}
    networks:
    - ft_transcendence_network
    container_name : front
    hostname: front
    command: npm run ${NODE_ENV}

  postgreSQL:
    image: postgres:14.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bob}
      POSTGRES_DB: ${POSTGRES_DATABASE:-ft_transcendance}
      PGDATA: /data/postgres
    volumes:
    - postgres_data:/data/postgres:Z
    restart: always
    networks:
    - ft_transcendence_network
    container_name : postgreSQL
    hostname: postgreSQL
    command: postgres -c stats_temp_directory=/tmp

  pgAdmin:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tglory@student.42Lyon.fr}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-foobar}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      PGADMIN_CONFIG_SERVER_MODE: "False" # Required to have more permission in containers, but remove connection with email & password to pgAdmin
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False" # If this is set to false, no one needs a "master password" to log in
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    - ./pgAdmin/servers.json:/pgadmin4/servers.json
    - ./pgAdmin/.pgpass:/pgadmin4/.pgpass
    restart: always
    ports:
    - ${PGADMIN_PORT}:${PGADMIN_PORT}
    networks:
    - ft_transcendence_network
    container_name : pgAdmin
    hostname: pgAdmin
    depends_on:
    - postgreSQL
# tricky way to set the right permissions on the file that contains the PostgreSQL database password
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/.pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/.pgpass;
      chown pgadmin /var/lib/pgadmin/.pgpass;
      /entrypoint.sh
      "

volumes:

  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/postgres_data

  pgadmin_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/pgadmin_data

networks:
  ft_transcendence_network:
    driver: bridge
