version: '3.8'

services:
  postgreSQL:
    image: postgres:14.4
    #build:
    #  context: ./requirements/postgreSQL/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bob}
      PGDATA: /data/postgres
    volumes:
    - db_postgres:/data/postgres
    restart: unless-stopped
    ports:
    - 5432:5432
    networks:
    - ft_transcendence_network
    container_name : postgreSQL
    hostname: postgreSQL
    command: postgres -c stats_temp_directory=/tmp

  pgAdmin:
    image: dpage/pgadmin4:2022-06-27-1
    #build:
    #  context: ./requirements/postgreSQL/
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tglory@student.42Lyon.fr}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-foobar}
      PGADMIN_LISTEN_PORT: 8080
 #     PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - db_pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    ports:
    - 8080:8080
    networks:
    - ft_transcendence_network
    container_name : pgAdmin
    hostname: pgAdmin
    depends_on:
    - postgreSQL

#  nginx:
#    build:
#      context: .
#      dockerfile: ./requirements/nginx/Dockerfile
#    restart: always
#    ports:
#    - 443:443
#    networks:
#    - ft_transcend_network
#    container_name : nginx
#    hostname: nginx
#    depends_on:
#    - wordpress
#    volumes:
#    - wpdata:/var/www/html/wordpress

volumes:
  db_postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/db_postgres
  db_pgadmin:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/ft_transcendence_volumes/db_pgadmin

networks:
  ft_transcendence_network:
    driver: bridge
