
name: Docker-compose tests

on: [push, pull_request]
jobs:
  dockerfile-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dockerfile-validator
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: "api/Dockerfile"

      - name: Run dockerfile-validator
        uses: ghe-actions/dockerfile-validator@v1
        with:
          dockerfile: "front-end/Dockerfile"

  docker-compose:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: dockerfile-validator

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Environnement Informations Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo OS version
          lsb_release -a
          echo
          echo Linux kernel version
          uname -r
          echo
          echo Current User
          whoami

      - name: Environnement Informations macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo OS version
          system_profiler SPSoftwareDataType
          echo
          echo Current User
          whoami
          echo
          echo Node version
          node --version
          echo
          echo NPM version
          npm version
          echo
          echo NestJS version
          npm version

      - name: Install Docker Linux
        if: matrix.os == 'ubuntu-latest'
        run : |
          DISTRO=`lsb_release -a 2> /dev/null | grep Distributor | awk -F ' ' '{print $3}' | tr '[:upper:]' '[:lower:]'`
          sudo apt update
          sudo apt install -y ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/$DISTRO/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/$DISTRO $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose docker-compose-plugin jq
        shell: bash

      - name: Install Homebrew MacOS
        if: matrix.os == 'macos-latest'
        run : |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

        shell: bash

      - name: Install Docker MacOS
        if: matrix.os == 'macos-latest'
        run : |
          brew install docker
          brew install docker-machine
          brew install docker-compose
        shell: bash

      - name: Docker Infos 
        run : |
          docker version
          docker-compose version
        shell: bash

      - name: Add 42API Credentials
        run : |
          ./credentials42.sh ${{ secrets.FT_UID }} ${{ secrets.FT_SECRET }}
        shell: bash

      - name: Setup containers
        run : |
          make setup -i
        shell: bash

      - name: Start containers
        run : |
          docker-compose up --detach
        shell: bash

      - name: Waiting for ready and close containers
        run : |
          docker-compose logs -f & ./autodocker.sh
        shell: bash
